First update
starknet-id/naming_contract pull request #16
Opened 2022-12-29 15:04 UTC by Th0rgal

This first update to the naming contract adds:

- A minimum requirement of 6 months for purchasing and renewing a domain.
Here is an example on testnet with a modified client which allows 0.1 years:
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/41830259/209971314-117261ef-ccc2-4fd9-81c0-4e4c01a51b09.png">

- A better check to know if you can write on a StarknetID: it allows you to rewrite a domain on a StarknetID if its domain expired. @0xBenaparte should we even keep a check for this? If we don't someone would be able to lose his domain ownership until it expires by calling the contract manually (given we already check on the client). This would mean less code, so a safer contract and it would be cheaper. 

It removes:
Whitelisting related code.

2022-12-29 15:26 UTC, Th0rgal commented
fix: #13

2022-12-29 17:17 UTC, 0xBenaparte commented
So if I write another random name on my starknet Id that already has a domain then I lose the ownership of the domain that I overrode ?

2022-12-29 17:20 UTC, 0xBenaparte commented on src/naming/registration.cairo
> +// We might remove it in the future and keep a clientisde check
Erreur dans le commentaire

2022-12-29 17:22 UTC, 0xBenaparte commented on src/naming/registration.cairo
> +            // because cairo is hell
Met moi une explication au moins mdrr

2022-12-29 17:23 UTC, 0xBenaparte commented on src/naming/registration.cairo
> +            tempvar syscall_ptr = syscall_ptr;
Sachant que tu fais dans le if et le else tu peux pas le faire avant ou après la boucle ?

2022-12-29 17:27 UTC, 0xBenaparte requested changes
Juste explication sur le if else et un petit problème de commentaire !

2022-12-31 07:54 UTC, Th0rgal commented
> So if I write another random name on my starknet Id that already has a domain then I lose the ownership of the domain that I overrode ?  

Yes that would be the idea if I removed the check. So we should check on the client side. To me it's like having a check in transfer() to see if you transfer your StarkNetID to the address 0 or a normal address. We should not do this contract side.

2022-12-31 07:56 UTC, Th0rgal commented on src/naming/registration.cairo
> +            tempvar syscall_ptr = syscall_ptr;
Nope là il s'agit d'unifier la position des pointeurs pour que les builtins soient corrects peu importe le branchement du programme. On aura plus ce genre de soucis en cairo 1.0. Tu peux essayer de faire des changements et compiler si tu veux check

2022-12-31 13:42 UTC, Th0rgal commented
J'ai enlevé le check (et donc le commentaire avec). Dis moi si ça te va @0xBenaparte . Est-ce que tu peux confirmer qu'on check bien qu'une starnet id n'a pas de domaine sur le client ?

2023-01-01 14:58 UTC, Th0rgal commented
replaced by #17

2023-01-01 14:58 UTC, closed without merging