Feat/subdomains
starknet-id/naming_contract pull request #25
Opened 2023-01-29 17:17 UTC by Th0rgal

This fixes the fact you couldn't reuse a subdomain after resetting all subdomains of a specific domain

2023-02-03 16:16 UTC, 0xBenaparte requested changes
Just a few changes/questions on the comments of the tests. 

Test coverage is increasing ;)

2023-02-03 16:16 UTC, 0xBenaparte commented on src/naming/main.cairo
> +func domain_to_data{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
This is cool and useful 👍

2023-02-03 16:16 UTC, 0xBenaparte commented on tests/integration/test_reset_subdomains.cairo
> +    // should mint a domain and create a subdomain
You only mint a domain, you don't create a subdomain here do you ?

2023-02-03 16:16 UTC, 0xBenaparte commented on tests/integration/test_reset_subdomains.cairo
> +    // should mint the subdomain again
You have to place this before the declaration of token_id3 in order for it to be clearer ;)

2023-02-03 16:16 UTC, 0xBenaparte commented on tests/integration/test_reset_subdomains.cairo
> +    assert token_id = token_id3;
Nice test gg

2023-02-13 20:54 UTC, fricoben commented
I marked this PR as 1 day in Only Dust but @Th0rgal told me that this PR and [this PR ](https://github.com/starknet-id/contract/pull/8) are one day (0.5 this one and 0.5 the other one). 

So consequently I'll not report this PR on [Only Dust](https://github.com/starknet-id/contract/pull/8)

2023-02-13 21:13 UTC, DeepMintingValue approved these changes

2023-02-13 21:16 UTC, fricoben approved these changes

2023-02-13 21:16 UTC, merged